name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "👋 Hello! Thanks for opening your first issue! We'll get back to you as soon as possible."
        pr-message: "🎉 Hi there! Thanks for opening your first pull request! We'll review it shortly."
